import Foundation

// Called by the GenerateSDKVersion build plugin.
// argv[1] = path to the output Swift file.
// Reads MARKETING_VERSION from the environment; falls back to "dev".

let outputPath = CommandLine.arguments[1]
let version = ProcessInfo.processInfo.environment["MARKETING_VERSION"] ?? "dev"

let source = """
// Auto-generated by GenerateSDKVersion build plugin — do not edit manually.
enum SDKVersion {
    static let current = "\(version)-ios"
}
"""

try source.write(toFile: outputPath, atomically: true, encoding: .utf8)
