import Foundation
import PackagePlugin

/// Build tool plugin that generates `SDKVersion+Generated.swift` before compilation.
/// Reads the version string directly from the `VERSION` file at the package root —
/// the single source of truth for the SDK version.
@main
struct GenerateSDKVersion: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) throws -> [Command] {
        let output = context.pluginWorkDirectory.appending("SDKVersion+Generated.swift")

        let versionFile = context.package.directory.appending("VERSION")
        let version = (try? String(contentsOfFile: versionFile.string))?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? "dev"

        let source = """
        // Auto-generated by GenerateSDKVersion build plugin — do not edit manually.
        // Source of truth: VERSION file at the repo root.
        enum SDKVersion {
            static let current = "\(version)-ios"
        }
        """
        try source.write(toFile: output.string, atomically: true, encoding: .utf8)

        return [
            .buildCommand(
                displayName: "Generate SDKVersion (\(version))",
                executable: Path("/usr/bin/true"),
                arguments: [],
                outputFiles: [output]
            )
        ]
    }
}
