import Foundation
import PackagePlugin

/// Build tool plugin that generates `SDKVersion+Generated.swift` before compilation.
///
/// The version string is read from the `MARKETING_VERSION` environment variable,
/// which xcodebuild propagates from build settings into every plugin/tool it
/// spawns. Falls back to `"dev"` for local Xcode / SPM builds where the var
/// is not set.
///
/// The file is written directly in the plugin's Swift code; `/usr/bin/true` is
/// declared as the "command" solely so the build system knows `outputFiles`
/// exists and adds it to the compile phase — no separate executable needed.
@main
struct GenerateSDKVersion: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) throws -> [Command] {
        let output = context.pluginWorkDirectory.appending("SDKVersion+Generated.swift")

        let version = ProcessInfo.processInfo.environment["MARKETING_VERSION"] ?? gitTag(in: context) ?? "dev"
        let source = """
        // Auto-generated by GenerateSDKVersion build plugin — do not edit manually.
        enum SDKVersion {
            static let current = "\(version)-ios"
        }
        """
        try source.write(toFile: output.string, atomically: true, encoding: .utf8)

        return [
            .buildCommand(
                displayName: "Generate SDKVersion (\(version))",
                executable: Path("/usr/bin/true"),
                arguments: [],
                outputFiles: [output]
            )
        ]
    }

    /// Returns the nearest git tag reachable from HEAD, or `nil` if git is unavailable
    /// or the repo has no tags. Used as a fallback for local source builds.
    private func gitTag(in context: PluginContext) -> String? {
        let task = Process()
        task.executableURL = URL(fileURLWithPath: "/usr/bin/git")
        // Run git relative to the package root so it finds the .git directory
        task.currentDirectoryURL = URL(fileURLWithPath: context.package.directory.string)
        task.arguments = ["describe", "--tags", "--abbrev=0"]
        let pipe = Pipe()
        task.standardOutput = pipe
        task.standardError = Pipe() // suppress error output
        guard (try? task.run()) != nil else { return nil }
        task.waitUntilExit()
        guard task.terminationStatus == 0 else { return nil }
        let raw = String(data: pipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let tag = raw.hasPrefix("v") ? String(raw.dropFirst()) : raw
        return tag.isEmpty ? nil : tag
    }
}
