name: Build Library

on: push

permissions:
  id-token: write
  contents: write

jobs:
  build-xcframework:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: echo "VERSION=build-${{ github.run_id }}" >> "$GITHUB_OUTPUT"

      - name: Build XCFramework
        id: build
        uses: ./.github/actions/build-xcframework
        with:
          marketing_version: ${{ steps.version.outputs.VERSION }}
          run_tests: "true"

      - name: Upload XCFramework artifact
        uses: actions/upload-artifact@v4
        with:
          name: BandwidthRTC-${{ steps.version.outputs.VERSION }}
          path: ${{ steps.build.outputs.zip_path }}
          retention-days: 3
